### ISSUE TITLE
Icons are very finicky with Android apps

### ISSUE THREAD

**Issue by ProjectMoon** [dseight/clockwork#1]
Hi, excellent project.

I'm using Clockwork to apply specific icons from the VaiDroid theme to specific Android apps, since a lot of the VaiDroid icons need to be updated to account for newer package versions. They work fine, but when restarting the phone, they are applied very inconsistently. Sometimes the Clockwork-applied icon will show up, then revert back to the regular Android app icon, even while I'm watching the home screen. Manually toggling the icon for the app fixes it, but doing this almost every time I restart the phone makes things difficult.

Edit: after some testing, might be related to the start of the android app support service.

**Comment by ProjectMoon** [comment]
This may also have something to do with Patchmanager, since it seems to happen after patchmanager runs. The only patches I'm using modify the maliit keyboard, however.

**Comment by dseight** [comment]
Thanks, I'll try to find a solution for this. Figured out that this issue is reproducible with stop/start of Android Support.

**Comment by ProjectMoon** [comment]
Yes, I found that too.

**Comment by dseight** [comment]
Should be fixed with [0.2.3](https://github.com/dseight/clockwork/releases/tag/0.2.3) release (see 5d2c3ba5f30543f9c9fd7e9e4566c1370f9b0a7f for details). 

Original Android icons may appear for a short period of time after aliendalvik restart, though.

**Comment by ProjectMoon** [comment]
Yes, looks like it fixes it.

**Comment by dseight** [comment]
It's nice to hear that :)

**Comment by ProjectMoon** [comment]
So there is at least one more circumstance under which this can fail. I had my home screen restart on me, not of my own will (probably some crash), and then it seems like the Android icons once again went back to their normal counterparts. Doing a normal homescreen start from utilities settings menu, it fixes the icons again (since Clockwork hooks into service restarts I guess).

**Comment by dseight** [comment]
> So there is at least one more circumstance under which this can fail. I had my home screen restart on me, not of my own will (probably some crash), and then it seems like the Android icons once again went back to their normal counterparts.

If there would be some easily-reproducible case, I'll take a look into one. But it would be better to open a new issue for it, anyway.
